// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA72AIFQNjAwPtYHP9c7Hjn58Tm0GF_iDA',
    appId: '1:821549797162:android:bd571dfa14e2fc91965853',
    messagingSenderId: '821549797162',
    projectId: 'elders-elettrico-c2a4a',
    storageBucket: 'elders-elettrico-c2a4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-dejlueDWeSQDHjllt0lLOghAvOhBdbY',
    appId: '1:821549797162:ios:7fcd866b2654a3f1965853',
    messagingSenderId: '821549797162',
    projectId: 'elders-elettrico-c2a4a',
    storageBucket: 'elders-elettrico-c2a4a.appspot.com',
    androidClientId: '821549797162-f7gt6bsrg6un9t1f79g00e7g4a8u55d9.apps.googleusercontent.com',
    iosClientId: '821549797162-f5kcbteh078s713631gknkb6sksucfh7.apps.googleusercontent.com',
    iosBundleId: 'com.elderselettrico.mobile',
  );
}
